FROM ubuntu:14.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yq \
            ca-certificates \
            build-essential \
            git \
            mercurial \
            curl \
            wget \
            --no-install-recommends
